# Basics and variables

In [1]:
2+3

5

In [2]:
9-6

3

In [3]:
4*6

24

In [4]:
6/2

3.0

In [5]:
5/2

2.5

In [6]:
5//2

2

In [7]:
8+2*6

20

In [8]:
8+6-

SyntaxError: invalid syntax (Temp/ipykernel_12532/1225811020.py, line 1)

In [9]:
(8+6)*3

42

In [10]:
2*2*2

8

In [11]:
2**3

8

In [13]:
10//3

3

In [15]:
10%3 #remainder

1

In [16]:
'amar'

'amar'

In [17]:
print('amar')

amar


In [18]:
print('amar's laptop)

SyntaxError: invalid syntax (Temp/ipykernel_12532/3044502457.py, line 1)

In [19]:
print("amar's laptop")

amar's laptop


In [20]:
print("amar "laptop"")

SyntaxError: invalid syntax (Temp/ipykernel_12532/1624376222.py, line 1)

In [21]:
print("amar 'laptop'")

amar 'laptop'


In [22]:
print('amar's "laptop"')

SyntaxError: invalid syntax (Temp/ipykernel_12532/432175893.py, line 1)

In [23]:
print('amar\'s "laptop"')

amar's "laptop"


In [24]:
'amar'+'amar'

'amaramar'

In [25]:
10*'amar'

'amaramaramaramaramaramaramaramaramaramar'

In [26]:
print('c:\docs\naveen')

c:\docs
aveen


In [27]:
print(r'c:\docs\naveen')

c:\docs\naveen


In [28]:
x=2

In [29]:
x+2

4

In [30]:
y=5

In [31]:
x+y

7

In [33]:
y=10

In [34]:
x+y

12

In [35]:
y

10

In [36]:
abc

NameError: name 'abc' is not defined

In [37]:
x+10

12

In [38]:
_+y

22

In [39]:
name = 'youtube'
print(name)

youtube


In [40]:
name + 'rocks'

'youtuberocks'

In [41]:
name 'rocks'

SyntaxError: invalid syntax (Temp/ipykernel_12532/639239415.py, line 1)

In [42]:
name[5]

'b'

In [43]:
name

'youtube'

In [44]:
name[-2]

'b'

In [45]:
name[10]

IndexError: string index out of range

In [46]:
name[1:3]

'ou'

In [47]:
name[1:]

'outube'

In [48]:
name[:4]

'yout'

In [49]:
name[3:15]

'tube'

In [50]:
name [0:4] = 'hello'

TypeError: 'str' object does not support item assignment

In [51]:
'my' + name[3:]

'mytube'

In [ ]:
len(name)

# Lists

In [53]:
nums = [2,3,4,5,6,7,8,8]
print(nums)

[2, 3, 4, 5, 6, 7, 8, 8]


In [54]:
nums[0]

2

In [55]:
nums[67]

IndexError: list index out of range

In [56]:
nums[-2]

8

In [57]:
names = ['n','d','k','k','b','g','r','f']

In [58]:
names

['n', 'd', 'k', 'k', 'b', 'g', 'r', 'f']

In [60]:
mil = [nums,names]

In [61]:
mil

[[2, 3, 4, 5, 6, 7, 8, 8], ['n', 'd', 'k', 'k', 'b', 'g', 'r', 'f']]

In [62]:
nums.append(56)

In [63]:
nums

[2, 3, 4, 5, 6, 7, 8, 8, 56]

In [64]:
nums.insert(2,44)

In [65]:
nums

[2, 3, 44, 4, 5, 6, 7, 8, 8, 56]

In [66]:
nums.remove(8)

In [67]:
nums

[2, 3, 44, 4, 5, 6, 7, 8, 56]

In [68]:
nums.pop(1)

3

In [69]:
nums

[2, 44, 4, 5, 6, 7, 8, 56]

In [70]:
nums.pop()

56

In [71]:
nums

[2, 44, 4, 5, 6, 7, 8]

In [72]:
del nums[2:]

In [73]:
nums

[2, 44]

In [74]:
nums.extend(29,12,34)

TypeError: list.extend() takes exactly one argument (3 given)

In [75]:
nums.extend([2,33,4,5,6])

In [76]:
nums

[2, 44, 2, 33, 4, 5, 6]

In [77]:
min(nums)

2

In [78]:
max(nums)

44

In [79]:
sum(nums)

96

In [80]:
nums.sort()

In [81]:
nums

[2, 2, 4, 5, 6, 33, 44]

# Tuple

In [82]:
tup = (21,2,3,45)

In [83]:
tup

(21, 2, 3, 45)

In [84]:
tup[1]

2

In [85]:
tup[1]=23

TypeError: 'tuple' object does not support item assignment

In [87]:
tup.count(2)

1

In [92]:
s = {2,3,45,6,7,8}

In [93]:
s

{2, 3, 6, 7, 8, 45}

In [100]:
s = {25,333,447,9,335,3,7}

In [104]:
s

{3, 7, 9, 25, 333, 335, 447}

In [105]:
s[2]

TypeError: 'set' object is not subscriptable

# dictionary

In [1]:
data = {1:'a',2:'d',4:'g',7:'f'}

In [2]:
data

{1: 'a', 2: 'd', 4: 'g', 7: 'f'}

In [3]:
data[3]

KeyError: 3

In [4]:
data[4]

'g'

In [115]:
print(data.get(3))

None


In [116]:
data.get(1,'Not found')

'a'

In [117]:
data.get(3,'Not found')

'Not found'

In [7]:
keys = ['a','d','g','c']
values = ['q','w','r','t']
data = dict(zip(keys,values))

In [8]:
data

{'a': 'q', 'd': 'w', 'g': 'r', 'c': 't'}

In [9]:
data['a']

'q'

In [10]:
data['z'] = '100'

In [11]:
data

{'a': 'q', 'd': 'w', 'g': 'r', 'c': 't', 'z': '100'}

In [12]:
prog = {'a':'python','b':'css','c':'java','d':['html','javascript'],'e':{'f':'php','g':'mysql'}}

In [13]:
prog

{'a': 'python',
 'b': 'css',
 'c': 'java',
 'd': ['html', 'javascript'],
 'e': {'f': 'php', 'g': 'mysql'}}

In [14]:
prog['d']

['html', 'javascript']

In [15]:
prog['d'][1]

'javascript'

In [16]:
prog['e'][1]

KeyError: 1

In [17]:
prog['e']['f']

'php'

In [18]:
prog['e']

{'f': 'php', 'g': 'mysql'}

# Help option

In [21]:
help()


Welcome to Python 3.9's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.9/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> topics

Here is a list of available topics.  Enter any topic name to get more help.

ASSERTION           DELETION            LOOPING             SHIFTING
ASSIGNMENT          DICTIONARIES        MAPPINGMETHODS      SLICINGS
ATTRIBUTEMETHODS    DICTIONARYLITERALS  MAPPINGS            SPECIALATTRIBUTES
ATTRIBUTES          DYNAMICFEATU

In [23]:
help('LISTS')

Mutable Sequence Types
**********************

The operations in the following table are defined on mutable sequence
types. The "collections.abc.MutableSequence" ABC is provided to make
it easier to correctly implement these operations on custom sequence
types.

In the table *s* is an instance of a mutable sequence type, *t* is any
iterable object and *x* is an arbitrary object that meets any type and
value restrictions imposed by *s* (for example, "bytearray" only
accepts integers that meet the value restriction "0 <= x <= 255").

+--------------------------------+----------------------------------+-----------------------+
| Operation                      | Result                           | Notes                 |
|================================|==================================|=======================|
| "s[i] = x"                     | item *i* of *s* is replaced by   |                       |
|                                | *x*                              |                 

# More on variables

In [26]:
num =5
print(id(num))

1984251718064


In [28]:
i = 's'
print(id(i))

1984253224688


In [29]:
a=10
b=a

In [30]:
print(id(a))

1984251718224


In [31]:
print(id(b))

1984251718224


In [32]:
type(a)

int

# Data types in python

In [1]:
num = 2.5

In [2]:
type(num)

float

In [3]:
k = float(4)

In [4]:
k

4.0

In [5]:
k = complex(3,6)

In [6]:
k

(3+6j)

In [11]:
bool = 3<8

In [13]:
bool

True

In [14]:
int(True)

1

In [15]:
int(False)

0

In [16]:
t = (4,5,6)
print(type(t))

<class 'tuple'>


In [17]:
l = [1,2,3]
print(type(l))

<class 'list'>


In [18]:
s = {1,2,4}
print(type(s))

<class 'set'>


In [19]:
s = "ert"
print(type(s))

<class 'str'>


In [20]:
range(10)

range(0, 10)

In [21]:
list(range(5,9))

[5, 6, 7, 8]

In [22]:
list(range(2,10,2))

[2, 4, 6, 8]

In [23]:
type(range(10))

range

In [24]:
d = {1:'w',2:'r'}
print(type(d))

<class 'dict'>


In [28]:
d = {'a':'1','b':'2','c':'3'}

In [29]:
d

{'a': '1', 'b': '2', 'c': '3'}

# OPERATORS

In [30]:
2+3

5

# NUMBER SYSTEM

In [31]:
bin(10)

'0b1010'

In [32]:
bin(5)

'0b101'

In [33]:
oct(25)

'0o31'

In [34]:
hex(25)

'0x19'

In [39]:
print(0b1010)

10


# SWAPPING

In [40]:
a = 10
b = 20

temp = a
a = b
b = temp

print(a,b)

20 10


In [41]:
a = 2
b = 3

a = a + b
b = a - b
a = a - b

print(a,b)

3 2


In [42]:
a = 4
b = 20

a = a ^ b
b = a ^ b
a = a ^ b

print(a,b)

20 4


In [43]:
a = 4
b = 20

a,b = b,a

print(a,b)

20 4


# BITWISE OPERATORS

In [44]:
#Complement
print(~2)

-3


In [45]:
12 & 13

12

# MATH FUNCTION

In [46]:
import math

x = math.sqrt(25)

In [47]:
x

5.0

In [49]:
print(math.floor(2.9))

2


In [50]:
print(math.ceil(2.2))

3


In [51]:
print(math.pow(3,2))

9.0


In [52]:
print(math.pi)

3.141592653589793


In [53]:
print(math.e)

2.718281828459045


# USER INPUT

In [55]:
x = int(input("Enter number 1 - "))
y = int(input("Enter number 2 - "))
print("product:",x*y)

Enter number 1 - 12
Enter number 2 - 5
product: 60


In [57]:
ch = input("Enter a character : ")
print(ch)

Enter a character : Hello
Hello


In [58]:
ch = input("Enter a character : ")[0]
print(ch)

Enter a character : Hello
H


In [61]:
result = eval(input("Enter expression:  "))
print(result)

Enter expression:  2+5*8
42


In [63]:
import sys
x = int(sys.argv[1])
y = int(sys.argv[2])
print(x+y)

ValueError: invalid literal for int() with base 10: '-f'

# If else

In [66]:
x = 12

if(x%2 == 0):
    print("Even")
else:
    print("Odd")

Even


# WHILE

In [71]:
i = 1
j = 5

while(i<5):
    print("repeat",i)
    while j>1:
        print("Second loop",j)
        j -= 1
    i += 1
    

repeat 1
Second loop 5
Second loop 4
Second loop 3
Second loop 2
repeat 2
repeat 3
repeat 4


In [72]:
i = 1

while(i<5):
    j = 5
    print("repeat",i)
    while j>1:
        print("Second loop",j)
        j -= 1
    i += 1
    

repeat 1
Second loop 5
Second loop 4
Second loop 3
Second loop 2
repeat 2
Second loop 5
Second loop 4
Second loop 3
Second loop 2
repeat 3
Second loop 5
Second loop 4
Second loop 3
Second loop 2
repeat 4
Second loop 5
Second loop 4
Second loop 3
Second loop 2


# FOR LOOP

In [74]:
x = "hello"

for i in x:
    print(i)

h
e
l
l
o


In [76]:
for i in range(20,2,-2):
    print(i)

20
18
16
14
12
10
8
6
4


In [77]:
for i in range(20,2,-2):
    if i%6==0:
        print(i)

18
12
6


# Break Continue Pass

In [79]:
for i in range(20,2,-2):
    if i%7 == 0:
        break
    print(i)

20
18
16


In [80]:
for i in range(20,2,-2):
    if i%3 == 0:
        continue
    print(i)

20
16
14
10
8
4


In [81]:
for i in range(20,2,-2):
    if i%3 == 0:
        pass
    print(i)

20
18
16
14
12
10
8
6
4


In [85]:
for i in range(20,2,-2):
    if i%5 == 0:
        pass #skip total loop
    print(i)

20
18
16
14
12
10
8
6
4


In [86]:
for i in range(1,20):
    if i%2 == 0:
        pass
    if i%2 != 0:
        print(i)

1
3
5
7
9
11
13
15
17
19


# PATTERNS

In [89]:
for i in range(5):
    for j in range(5):
        print("#",end="")
    print()

#####
#####
#####
#####
#####


In [93]:
for i in range(5):
    for j in range(i+1):
        print("#",end="")
    print()

#
##
###
####
#####


In [95]:
for i in range(5):
    for j in range(5-i):
        print("#",end='')
    print()

#####
####
###
##
#


# For Else

In [97]:
nums = [1,2,5,7,8,0,35,6,7,85]

for num in nums:
    if num%5 == 0:
        print(num)
        break

5


In [102]:
nums = [1,2,5,7,8,35,6,7,85]

for num in nums:
    if num%9 == 0:
        print(num)
    else:
        print("Not found")

Not found
Not found
Not found
Not found
Not found
Not found
Not found
Not found
Not found


In [103]:
nums = [1,2,5,7,8,35,6,7,85]

for num in nums:
    if num%9 == 0:
        print(num)
else:
    print("Not found")

Not found


In [104]:
nums = [1,2,5,7,8,35,6,7,85]

for num in nums:
    if num%5 == 0:
        print(num)
else:
    print("Not found")

5
35
85
Not found


In [108]:
nums = [1,2,5,7,8,35,6,7,85]

for num in nums:
    if num%5 == 0:
        print(num)
        break
else:
    print("Not found")

5


# Prime numbers

In [111]:
num = 4
for i in range(2,num):
    if num%i == 0:
        print("Not prime")
        break
else:
    print("Prime")

Not prime


# ARRAY

In [115]:
import array as arr

val = arr.array('i',[3,4,51,6,-7])

print(val)

array('i', [3, 4, 51, 6, -7])


In [116]:
val.reverse()

In [117]:
val

array('i', [-7, 6, 51, 4, 3])

In [120]:
for i in range(len(val)):
    print(val[i])

-7
6
51
4
3


In [121]:
val = arr.array('u',['e','r','t'])

In [122]:
val

array('u', 'ert')

In [123]:
for i in range(len(val)):
    print(val[i])

e
r
t


In [126]:
val = arr.array('i',[3,4,51,6,-7])

In [131]:
newarr = arr.array(val.typecode,(a for a in val))

In [132]:
newarr

array('i', [3, 4, 51, 6, -7])

In [133]:
newarr = arr.array(val.typecode,(a*a for a in val))

In [134]:
newarr

array('i', [9, 16, 2601, 36, 49])

In [135]:
i = 0
while i<len(newarr):
    print(newarr[i])
    i = i+1

9
16
2601
36
49


In [139]:
from array import *

arr = array('i',[])

n = int(input("Enter the length of the array"))

for i in range(n):
    x = int(input())
    arr.append(x)

print(arr)

Enter the length of the array5
4
7
3
8
4
array('i', [4, 7, 3, 8, 4])


In [144]:
val = int(input("Enter the value to search"))
k = 0
for i in arr:
    if i == val:
        print("Element found at : ",k)
        break
    k += 1
else: 
    print("not found")

Enter the value to search4
Element found at :  0


In [147]:
print(arr.index(4))

0


# NUMPY

In [6]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [10]:
import numpy as np
arr = np.array([1,2,3.0])
print(arr.dtype)

float64


In [11]:
print(arr)

[1. 2. 3.]


In [12]:
arr = np.array([1,2,3],float)

In [13]:
arr

array([1., 2., 3.])

In [16]:
arr = np.linspace(1,15,5)

In [17]:
arr

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [18]:
arr = np.linspace(1,15,10)

In [19]:
arr

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [20]:
arr = np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [21]:
arr = np.logspace(1,15,5)
print(arr)

[1.00000000e+01 3.16227766e+04 1.00000000e+08 3.16227766e+11
 1.00000000e+15]


In [26]:
print('%.2f' %arr[4])

1000000000000000.00


In [27]:
arr = np.zeros(5)

In [28]:
arr

array([0., 0., 0., 0., 0.])

In [29]:
arr = np.ones(5,int)

In [30]:
arr

array([1, 1, 1, 1, 1])

In [31]:
arr = np.array([1,2,3,4,5])
arr += 5
print(arr)

[ 6  7  8  9 10]


In [34]:
arr = np.array([30,45,90])
print(np.sin(arr))

[-0.98803162  0.85090352  0.89399666]


In [35]:
print(np.log(arr))

[3.40119738 3.80666249 4.49980967]


In [36]:
print(np.sqrt(arr))

[5.47722558 6.70820393 9.48683298]


In [37]:
print(sum(arr))

165


In [38]:
print(min(arr))

30


In [39]:
arr1 = np.array([2,3,4,5,6])

arr2 = arr1 

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

#aliasing

[2 3 4 5 6]
[2 3 4 5 6]
2369041663728
2369041663728


In [43]:
arr1 = np.array([2,3,4,5,6])

arr2 = arr1.view()

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[2 3 4 5 6]
[2 3 4 5 6]
2369041663056
2369041632112


In [44]:
arr1 = np.array([2,3,4,5,6])

arr2 = arr1.view()

arr1[1] = 7   #shallow copy

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[2 7 4 5 6]
[2 7 4 5 6]
2369041663440
2369041663920


In [45]:
arr1 = np.array([2,3,4,5,6])

arr2 = arr1.copy()

arr1[1] = 7

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[2 7 4 5 6]
[2 3 4 5 6]
2369041664784
2369041664016


In [46]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
arr1.shape

(3, 3)

In [48]:
arr1.size

9

In [49]:
arr2 = arr1.flatten()

In [50]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr1.dtype

dtype('int32')

In [52]:
arr1.ndim  #dimesional

2

In [53]:
arr2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2.reshape(1,1,9)

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [58]:
m = np.matrix(arr1)

In [59]:
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
m = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [61]:
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
print(np.diagonal(m))

[1 5 9]


In [64]:
m.min()

1

In [65]:
m1 = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [66]:
m2 = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [68]:
m3 = m1 * m2

In [69]:
m3

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

# FUNCTIONS

In [70]:
def add(x,y):
    c = x+y
    print(c)
    
add(5,6)
add(11,23)

11
34


In [71]:
def add(x,y):
    c = x+y
    return c
    
result = add(5,6)
print(result)

11


In [72]:
def add(x,*y):
    c = x
    for i in y:
        c = c+i
    return c
    
result = add(5,6,5,6,7)
print(result)

29


In [76]:
def person(x,**y):
    print(x)
    print(y)
    
person('naveen', age = 28, city = 'hyderabad', mobile = 991212)

naveen
{'age': 28, 'city': 'hyderabad', 'mobile': 991212}


In [78]:
def person(x,**y):
    print(x)
    for i,j in y.items():
        print(i,j)
    
person('naveen', age = 28, city = 'hyderabad', mobile = 991212)

naveen
age 28
city hyderabad
mobile 991212


In [79]:
def person(**y):
    for i,j in y.items():
        print(i,j)
    
person(name = 'naveen', age = 28, city = 'hyderabad', mobile = 991212)

name naveen
age 28
city hyderabad
mobile 991212


# Global and Local variables

In [82]:
a = 10

def vari():
    a = 15
    print ("inside",a)

vari()
print ("otside",a)

inside 15
otside 10


In [84]:
a = 10
print(id(a))
print(a)

def vari():
    a = 15
    
    x = globals()['a']
    print(id(x))
    print ("inside",a,x)
    
    globals()['a'] = 15

vari()
print ("otside",a)

2368939059792
10
2368939059792
inside 15 10
otside 15


# FUNCTIONS

In [88]:
def count(x):
    even = 0
    odd = 0
    for i in x:
        if i%2 == 0:
            even += 1
        else:
            odd += 1
    return odd, even

lst = [2,3,45,56,7,8,69,43]

even, odd = count(lst)

print(even ,  odd)

5 3


# Fibonacci  Series & Factorial

In [94]:
def fibo(x):
    a = 0
    b = 1
    f = [0,1]
    for i in range(x-2):
        c = a+b
        f.append(a+b)
        a = b
        b = c
        
    print(f)
    
x = int(input("Enter length"))
fibo(x)

Enter length9
[0, 1, 1, 2, 3, 5, 8, 13, 21]


In [98]:
def fact(x):
    y = 1
    for i in range(1,x+1):
        y = y * i
        
    print(y)
    
x = int(input("Enter number"))
fact(x)

Enter number7
5040


# Recursion

In [1]:
def fact(x):
    if x == 1 :
        return 1
    else:
        return x*fact(x-1)
    

x = int(input("Enter number"))
z = fact(x)

print(z)

Enter number10
3628800


# LAMBDA

In [1]:
f = lambda a : a*a

result = f(5)

print(result)

25


In [4]:
f = lambda a,b : a+b

result = f(5,6)

print(result)

11


# Constructor, Self, Comparing Objects

In [1]:
class computer():
    
    def __init__(self):
        self.name = "Shiva"
        self.age = 28
        
    def update(self):
        self.age = 30

c1 = computer()
c2 = computer()

c1.name = "Rakhi"
c1.age = 29

print(c1.name, c1.age)
print(c2.name, c2.age)

Rakhi 29
Shiva 28


In [2]:
class computer():
    
    def __init__(self):
        self.name = "Shiva"
        self.age = 28
        
    def update(self):
        self.age = 30

c1 = computer()
c2 = computer()

c1.name = "Rakhi"
c1.age = 29

c1.update()

print(c1.name, c1.age)
print(c2.name, c2.age)

Rakhi 30
Shiva 28


In [3]:
class computer():
    
    def __init__(self):
        self.name = "Shiva"
        self.age = 28
        

c1 = computer()
c2 = computer()


print(c1.name, c1.age)
print(c2.name, c2.age)

Shiva 28
Shiva 28


In [7]:
class computer():
    
    def __init__(self):
        self.name = "Shiva"
        self.age = 28
        
    def update(self):
        self.age = 30
        
    def compare(self,other):
        if self.age == other.age:
            return True
        else:
            return False

c1 = computer()
c2 = computer()

c1.name = "Rakhi"
c1.age = 28

if c1.compare(c2):
    print("They are same")
else:
    print("They are different")

c1.update()


print(c1.name, c1.age)
print(c2.name, c2.age)

They are same
Rakhi 30
Shiva 28


In [8]:
class computer():
    
    def __init__(self):
        self.name = "Shiva"
        self.age = 28
        
    def update(self):
        self.age = 30
        
    def compare(self,other):
        if self.age == other.age:
            return True
        else:
            return False

c1 = computer()
c2 = computer()

c1.name = "Rakhi"
c1.age = 28


c1.update()

if c1.compare(c2):
    print("They are same")
else:
    print("They are different")

print(c1.name, c1.age)
print(c2.name, c2.age)

They are different
Rakhi 30
Shiva 28


In [5]:
class car:
    
    
    
    def __init__(self):
        self.milage = 10
        self.company = "BMW"
        
c1 = car()
c2 = car()

c1.milage = 8

print(c1.milage, c1.company)
print(c2.milage, c2.company)

8 BMW
10 BMW


In [6]:
class car:
    
    wheels = 4
    
    def __init__(self):
        self.milage = 10
        self.company = "BMW"
        
c1 = car()
c2 = car()

c1.milage = 8

print(c1.milage, c1.company, c1.wheels)
print(c2.milage, c2.company, c2.wheels)

8 BMW 4
10 BMW 4


In [8]:
class car:
    
    wheels = 4
    
    def __init__(self):
        self.milage = 10
        self.company = "BMW"
        
c1 = car()
c2 = car()

c1.milage = 8

car.wheels = 5

print(c1.milage, c1.company, c1.wheels)
print(c2.milage, c2.company, c2.wheels)

8 BMW 5
10 BMW 5


# Types of Methods

In [12]:
class student:
    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
    
    def avg(self):
        return (self.m1 + self.m2 + self.m3)/3
        
        
s1 = student(23,45,65)
s2 = student(54,86,90)

print(s1.avg())

44.333333333333336


In [15]:
class student:
    
    school = "Telusko"
    
    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
    
    def avg(self):
        return (self.m1 + self.m2 + self.m3)/3
    
    @classmethod
    def info(cls):
        return cls.school
    
        
        
s1 = student(23,45,65)
s2 = student(54,86,90)

print(student.info())

Telusko


In [18]:
class student:
    
    school = "Telusko"
    
    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
    
    def avg(self):
        return (self.m1 + self.m2 + self.m3)/3
    
    @classmethod
    def info1(cls):
        return cls.school
    
    @staticmethod
    def info():
        print("This is class method")
    
        
        
s1 = student(23,45,65)
s2 = student(54,86,90)

print(student.info1())
print(student.info())

Telusko
This is class method
None


# Inner Class

In [3]:
class student:
    
    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno
        
s1 = student('navin', 3)

print(s1.name, s1.rollno)

navin 3


In [4]:
class student:
    
    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno
        
    def show(self):
        print(self.name, self.rollno)
        
s1 = student('navin', 3)

s1.show()

navin 3


In [5]:
class student:
    
    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno
        
    def show(self):
        print(self.name, self.rollno)
        
    class laptop:
        
        def __init__(self):
            self.brand = 'HP'
            self.cpu = 'i5'
            self.ram = 8
        
s1 = student('navin', 3)

s1.show()

print(s1.laptop())

navin 3


In [7]:
class student:
    
    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno
        self.lap = self.laptop()
        
    def show(self):
        print(self.name, self.rollno)
        self.lap.show()
        
    class laptop:
        
        def __init__(self):
            self.brand = 'HP'
            self.cpu = 'i5'
            self.ram = 8
            
        def show(self):
            print(self.brand, self.cpu, self.ram)
        
s1 = student('navin', 3)

s1.show()

navin 3
HP i5 8


In [12]:
class student:
    
    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno
        
    def show(self):
        print(self.name, self.rollno)
        
    class laptop:
        
        def __init__(self):
            self.brand = 'HP'
            self.cpu = 'i5'
            self.ram = 8
            
        def show(self):
            print(self.brand, self.cpu, self.ram)
        
s1 = student('navin', 3)

s1.show()

lap = student.laptop()
print(lap.brand)
lap.show()

navin 3
HP
HP i5 8


# Inheritance

In [16]:
class A:
    
    def feature1(self):
        print("Feature 1 working")
        
    def feature2(self):
        print("Feature 2 working")
        
class B:
    
    def feature3(self):
        print("Feature 3 working")
        
    def feature4(self):
        print("Feature 4 working")
        
a1 = A()

a1.feature1()
        
b1 = B()

b1.feature3()

Feature 1 working
Feature 3 working


In [18]:
class A:
    
    def feature1(self):
        print("Feature 1 working")
        
    def feature2(self):
        print("Feature 2 working")
        
class B(A):
    
    def feature3(self):
        print("Feature 3 working")
        
    def feature4(self):
        print("Feature 4 working")
        
class C(B):
    
    def feature5(self):
        print("Feature 5 working")
        
    def feature6(self):
        print("Feature 6 working")
        
a1 = A()

a1.feature1()
        
b1 = B()

b1.feature3()

c1 = C()

c1.feature2()

Feature 1 working
Feature 3 working
Feature 2 working


In [19]:
class A:
    
    def feature1(self):
        print("Feature 1 working")
        
    def feature2(self):
        print("Feature 2 working")
        
class B:
    
    def feature3(self):
        print("Feature 3 working")
        
    def feature4(self):
        print("Feature 4 working")
        
class C(A,B):
    
    def feature5(self):
        print("Feature 5 working")
        
    def feature6(self):
        print("Feature 6 working")
        
a1 = A()

a1.feature1()
        
b1 = B()

b1.feature3()

c1 = C()

c1.feature2()

Feature 1 working
Feature 3 working
Feature 2 working


In [22]:
class A:
    
    def __init__(self):
        print("In A init")
    
    def feature1(self):
        print("Feature 1 working")
        
    def feature2(self):
        print("Feature 2 working")
        
class B:
    
    def __init__(self):
        print("In B init")
    
    def feature3(self):
        print("Feature 3 working")
        
    def feature4(self):
        print("Feature 4 working")
        
class C(A,B):
    
    def __init__(self):
        print("In C init")
    
    def feature5(self):
        print("Feature 5 working")
        
    def feature6(self):
        print("Feature 6 working")
        
c1 = C()

c1.feature2()

In C init
Feature 2 working


In [29]:
class A:
    
    def __init__(self):
        print("In A init")
    
    def feature1(self):
        print("Feature 1 working")
        
    def feature2(self):
        print("Feature 2 working")
        
class B(A):
    
    def __init__(self):
        print("In B init")
    
    def feature3(self):
        print("Feature 3 working")
        
    def feature4(self):
        print("Feature 4 working")
        
class C(B):
    
    def __init__(self):
        super().__init__()
        print("In C init")
    
    def feature5(self):
        print("Feature 5 working")
        
    def feature6(self):
        print("Feature 6 working")
        
c1 = C()

c1.feature2()

In B init
In C init
Feature 2 working


In [30]:
class A:
    
    def __init__(self):
        print("In A init")
    
    def feature1(self):
        print("Feature 1 working")
        
    def feature2(self):
        print("Feature 2 working")
        
class B:
    
    def __init__(self):
        print("In B init")
    
    def feature3(self):
        print("Feature 3 working")
        
    def feature4(self):
        print("Feature 4 working")
        
class C(A,B):
    
    def __init__(self):
        super().__init__()
        print("In C init")
    
    def feature5(self):
        print("Feature 5 working")
        
    def feature6(self):
        print("Feature 6 working")
        
c1 = C()

c1.feature2()

In A init
In C init
Feature 2 working


In [31]:
class A:
    
    def __init__(self):
        print("In A init")
    
    def feature1(self):
        print("Feature 1 working")
        
    def feature2(self):
        print("Feature 2 working")
        
class B:
    
    def __init__(self):
        print("In B init")
    
    def feature3(self):
        print("Feature 3 working")
        
    def feature4(self):
        print("Feature 4 working")
        
class C(B,A):
    
    def __init__(self):
        super().__init__()
        print("In C init")
    
    def feature5(self):
        print("Feature 5 working")
        
    def feature6(self):
        print("Feature 6 working")
        
c1 = C()

c1.feature2()

In B init
In C init
Feature 2 working


In [34]:
class A:
    
    def __init__(self):
        print("In A init")
    
    def feature1(self):
        print("Feature 1-A working")
        
    def feature2(self):
        print("Feature 2 working")
        
class B:
    
    def __init__(self):
        print("In B init")
    
    def feature1(self):
        print("Feature 1-B working")
        
    def feature4(self):
        print("Feature 4 working")
        
class C(A,B):
    
    def __init__(self):
        super().__init__()
        print("In C init")
    
    def feature5(self):
        print("Feature 5 working")
        
    def feature6(self):
        super().feature2()
        
        
c1 = C()

c1.feature1()
c1.feature1()

c1.feature6()

In A init
In C init
Feature 1-A working
Feature 1-A working
Feature 2 working


# Polymorphism

# Duct typing

In [47]:
class PyCharm:
    
    def execute(self):
        print("Compiling")

class laptop:
    
    def code(self, ide):
        ide.execute()
        
        
ide = PyCharm()

lap1 = laptop()
lap1.code(ide)

Compiling


In [48]:
class PyCharm:
    
    def execute(self):
        print("Compiling")
        
class Myeditor:
    
    def execute(self):
        print("Checking done")

class laptop:
    
    def code(self, ide):
        ide.execute()
        
        
ide = Myeditor()

lap1 = laptop()
lap1.code(ide)

Checking done


# Operator Overloading

In [49]:
a = 7
b = 9

print(a + b)

print(int.__add__(a,b))

16
16


In [50]:
a = '7'
b = '9'

print(a + b)

print(str.__add__(a,b))

79
79


In [51]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
        
s1 = student(35,67)
s2 = student(66,88)

s3 = s1 + s2

TypeError: unsupported operand type(s) for +: 'student' and 'student'

In [53]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        s3 = student(m1, m2)
        
        return s3
        
        
s1 = student(35,67)
s2 = student(66,88)

s3 = s1 + s2

print(s3.m1, s3.m2)

101 155


In [54]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        s3 = student(m1, m2)
        
        return s3
    
    def __gt__(self, other):
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        if r1 > r2:
            return True
        else:
            return False
        
        
        
s1 = student(35,67)
s2 = student(66,88)

s3 = s1 + s2

print(s3.m1, s3.m2)

if s1>s2:
    print("S1 wins")
    
else:
    print("S2 wins")

101 155
S2 wins


In [60]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        s3 = student(m1, m2)
        
        return s3
    
    def __gt__(self, other):
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        if r1 > r2:
            return True
        else:
            return False        
        
        
s1 = student(35,67)
s2 = student(66,88)
    
    
print(s1)

In [63]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        s3 = student(m1, m2)
        
        return s3
    
    def __gt__(self, other):
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        if r1 > r2:
            return True
        else:
            return False
        
    def __str__(self):
        return self.m1, self.m2
        
        
        
s1 = student(35,67)
s2 = student(66,88)
    
    
print(s1.__str__())

(35, 67)


In [65]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def __add__(self, other):
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        s3 = student(m1, m2)
        
        return s3
    
    def __gt__(self, other):
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        if r1 > r2:
            return True
        else:
            return False
        
    def __str__(self):
        return '{} {} '.format(self.m1, self.m2)
        
        
        
s1 = student(35,67)
s2 = student(66,88)
    
    
print(s1)

35 67 


#  Method Overloading

In [66]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def sum(self, a, b):
        s = a + b
        
        return s
        
        
s1 = student(35,67)
s2 = student(66,88)
    
    
print(s1.sum(4,5))

9


In [69]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def sum(self, a=None, b=None, c=None):
        if a!=None and b!=None and c!=None:
            s = a + b + c
        elif a!=None and b!=None:
            s = a + b
        else:
            s = a
        
        return s
        
        
s1 = student(35,67)
s2 = student(66,88)
    
    
print(s1.sum(4,5))

9


In [70]:
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def sum(self, a=None, b=None, c=None):
        if a!=None and b!=None and c!=None:
            s = a + b + c
        elif a!=None and b!=None:
            s = a + b
        else:
            s = a
        
        return s
        
        
s1 = student(35,67)
s2 = student(66,88)
    
    
print(s1.sum(4,5,10))

19


# Method Overriding

In [71]:
class A:
    
    def show(self):
        print("In A show")
        
class B(A):
    pass

a1 = B()

a1.show()

In A show


In [72]:
class A:
    
    def show(self):
        print("In A show")
        
class B(A):
    
    def show(self):
        print("In B show")

a1 = B()

a1.show()

In B show


# Abstract Classes and Abstract method

In [7]:
from abc import ABC, abstractmethod

class computer:
    @abstractmethod
    def process(self):
        pass
    
class Laptop(computer):
    pass
    
#com = computer()
com1 = Laptop()
#com.process()

# Iterator